// Codes d'erreur centralisés pour l'application
// Format: CATEGORIE_DESCRIPTION

const ERROR_CODES = {
    // Erreurs d'authentification (AUTH_*)
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
    AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
    
    // Erreurs utilisateur (USER_*)
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
    USER_INVALID_DATA: 'USER_INVALID_DATA',
    
    // Erreurs produit (PRODUCT_*)
    PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
    PRODUCT_ALREADY_EXISTS: 'PRODUCT_ALREADY_EXISTS',
    PRODUCT_INSUFFICIENT_STOCK: 'PRODUCT_INSUFFICIENT_STOCK',
    PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',
    PRODUCT_INVALID_DATA: 'PRODUCT_INVALID_DATA',
    
    // Erreurs commande (ORDER_*)
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
    ORDER_ALREADY_DELIVERED: 'ORDER_ALREADY_DELIVERED',
    ORDER_CANNOT_CANCEL: 'ORDER_CANNOT_CANCEL',
    ORDER_INVALID_STATUS: 'ORDER_INVALID_STATUS',
    ORDER_EMPTY_ITEMS: 'ORDER_EMPTY_ITEMS',
    
    // Erreurs de validation (VALIDATION_*)
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    VALIDATION_MISSING_FIELD: 'VALIDATION_MISSING_FIELD',
    VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
    VALIDATION_INVALID_TYPE: 'VALIDATION_INVALID_TYPE',
    
    // Erreurs de permission (PERMISSION_*)
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    PERMISSION_FORBIDDEN: 'PERMISSION_FORBIDDEN',
    PERMISSION_NOT_OWNER: 'PERMISSION_NOT_OWNER',
    
    // Erreurs de ressource (RESOURCE_*)
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
    RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
    
    // Erreurs serveur (SERVER_*)
    SERVER_ERROR: 'SERVER_ERROR',
    SERVER_DATABASE_ERROR: 'SERVER_DATABASE_ERROR',
    SERVER_UNAVAILABLE: 'SERVER_UNAVAILABLE',
    
    // Erreurs de route (ROUTE_*)
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    ROUTE_METHOD_NOT_ALLOWED: 'ROUTE_METHOD_NOT_ALLOWED',
    
    // Erreurs de rate limit (RATE_LIMIT_*)
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};

module.exports = ERROR_CODES;
